development: &defaults
  image_host: 'http://localhost:3000'
  carrierwave:
    root: 'public/pictures'
test:
  <<: *defaults
  image_host: 'http://test.host'
  carrierwave:
    root: 'test'

staging:
  image_host: 'http://monumentr.tech'
  carrierwave:
    root: 'public/pictures'

production:
  image_host: 'http://monumentr.herokuapp.com'
  carrierwave:
    root: 'public/pictures'
